<?php  //[STAMP] 196cd182813c7bf9a85b4d6ccf7f613d
namespace PrivateIT\modules\morphology\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use PrivateIT\modules\morphology\tests\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
